version: 2

# Список включенных линтеров
linters:
  enable:
    - errcheck       # Проверка необработанных ошибок
    - govet          # Встроенный статический анализатор Go
    - staticcheck    # Анализатор кода с советами по оптимизации
    - ineffassign    # Поиск неиспользуемых переменных
    - deadcode       # Поиск неиспользуемого кода
    - typecheck      # Проверка типов
    - unused         # Проверка неиспользуемых переменных
    - structcheck    # Поиск неиспользуемых полей в структурах
    - varcheck       # Поиск неиспользуемых переменных
    - gofumpt        # Улучшенный форматтер кода (альтернатива gofmt)
    - gocritic       # Расширенные проверки кода
    - goconst        # Вынос повторяющихся строк и чисел в константы
    - gosec          # Поиск уязвимостей в коде
    - stylecheck     # Проверка соответствия стилю Go
    - exportloopref  # Проверка ошибок замыкания в циклах
    - forbidigo      # Запрет на использование определенных конструкций
    - depguard       # Ограничение импорта нежелательных пакетов

  # Список отключенных линтеров (если они включены по умолчанию)
  disable:
    - lll            # Ограничение длины строк (можно включить при необходимости)
    - godot          # Требование точки в конце комментариев (можно включить при необходимости)

# Настройки линтеров
linters-settings:
  errcheck:
    check-type-assertions: true  # Проверять ошибки при type assertion
    check-blank: true            # Проверять игнорируемые ошибки (например, `_ = someFunc()`)

  gofumpt:
    extra-rules: true  # Включение дополнительных правил форматирования

  gocritic:
    enabled-checks:
      - all  # Включить все проверки gocritic

  goconst:
    min-len: 3        # Минимальная длина строки для вынесения в константы
    min-occurrences: 3 # Минимальное количество повторений для вынесения в константы

  gosec:
    excludes:
      - G104 # Исключить проверку использования `fmt.Errorf("%v", err)` вместо `fmt.Errorf("%w", err)`

# Настройки вывода
run:
  timeout: 5m  # Ограничение времени работы линтеров (по умолчанию 5 минут)
  tests: true  # Анализировать также файлы с тестами
  modules-download-mode: vendor # Использовать go modules и vendor

# Исключение отдельных директорий/файлов
exclude-dirs:
  - vendor
  - migrations
  - testdata

# Исключение отдельных сообщений линтера по регулярным выражениям
issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "error return value not checked" # Игнорировать определенные ошибки errcheck

    - linters:
        - gosec
      text: "G304" # Игнорировать использование небезопасных путей

# Настройки вывода ошибок
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true