version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=5432
      - DB_CONTAINER_PORT=5435
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=merch_shop
      - DB_HOST=database
      - DB_SSLMODE=disable
      - SERVER_PORT=
      - DB_TEST_NAME=merch_shop_test
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merch_shop
      POSTGRES_DB_TEST: merch_shop_test
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d merch_shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal: